<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/xhtml" style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">&#13;
<head>&#13;
<meta name="viewport" content="width=device-width" />&#13;
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />&#13;
<title>Samba Smoothie</title>&#13;
&#13;
&#13;
</head>&#13;
&#13;
<body style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none; width: 100% !important; height: 100%; line-height: 1.6em; background-color: #f6f6f6; margin: 0; padding: 0;" bgcolor="#f6f6f6">&#13;
&#13;
<table style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; width: 100%; background-color: #f6f6f6; margin: 0;" bgcolor="#f6f6f6">&#13;
    <tr style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">&#13;
        <td style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0;" valign="top"></td>&#13;
        <td width="600" style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; display: block !important; max-width: 600px !important; clear: both !important; width: 100% !important; margin: 0 auto; padding: 0;" valign="top">&#13;
            <div style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; max-width: 600px; display: block; margin: 0 auto; padding: 0;">&#13;
                <table width="100%" cellpadding="0" cellspacing="0" style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; border-radius: 3px; background-color: #fff; margin: 0; border: 1px solid #e9e9e9;" bgcolor="#fff">&#13;
                    <tr style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">&#13;
                        <td style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 10px;" valign="top">&#13;
                            <table width="100%" cellpadding="0" cellspacing="0" style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">&#13;
                                <tr style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">&#13;
                                    <td style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; text-align: center; margin: 0; padding: 0 0 20px;" align="center" valign="top">&#13;
                                        <img src="${grailsApplication.config.serverAddress}assets/samba.png" style="width: 200px; font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; max-width: 100%; margin: 0;" />&#13;
                                    </td>&#13;
                                </tr>&#13;
                                <tr style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">&#13;
                                    <td style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;" valign="top">&#13;
                                       <h1 style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 22px !important; color: #76bc1e; line-height: 1.2em; font-weight: 800 !important; margin: 20px 0 5px;">Solicitud de activación de cuenta de usuario</h1>&#13;
                                    </td>&#13;
                                </tr>&#13;
                                <tr style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">&#13;
                                    <td style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;" valign="top">&#13;
                                        De la manera mas atenta le solicito me pueda activar mi cuenta de usuario para acceder a los servicios de Samba Smoothie desde
										la aplicación móvil&#13;
                                    </td>&#13;
                                </tr>&#13;
                                <tr style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">&#13;
                                    <td style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 0 20px;" valign="top">&#13;
                                        <strong style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">Correo electrónico:</strong> ${email}&#13;
                                    </td>&#13;
                                </tr>&#13;
                                <tr style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">&#13;
                                    <td style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 0 20px;" valign="top">&#13;
                                        <strong style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">Nombre:</strong> ${password}&#13;
                                    </td>&#13;
                                </tr>&#13;
                                <tr style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">&#13;
                                    <td style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;" valign="top">&#13;
                                         &#13;
                                    </td>&#13;
                                </tr>&#13;
                                
                            </table>&#13;
                        </td>&#13;
                    </tr>&#13;
                </table>&#13;
                <div style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; width: 100%; clear: both; color: #999; margin: 0; padding: 20px;">&#13;
                    <table width="100%" style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">&#13;
                        <tr style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">&#13;
                            <td style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 12px; vertical-align: top; color: #999; text-align: center; margin: 0; padding: 0 0 20px;" align="center" valign="top">© 2017 Samba Smoothie</td>&#13;
                        </tr>&#13;
                    </table>&#13;
                </div></div>&#13;
        </td>&#13;
        <td style="font-family: Verdana, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0;" valign="top"></td>&#13;
    </tr>&#13;
</table>&#13;
&#13;
</body>&#13;
</html>
